# Generated by Django 2.2.4 on 2019-08-25 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpeople', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='person_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
